const PrivacyPolicy = () => {
    return (
        <pre style={{ width: '90%', margin: '10% 5% 0 5%', textAlign: 'center', overflowX: 'auto' }}>
            Privacy Policy <br />
            Last update: July 15, 2024 <br />
            1. Introduction <br />
            This Privacy Policy applies to the website https://vibrantwear.vercel.app (hereinafter the “website”) <br />
            published by the company (hereinafter “VibrantWear” or “we”) and its other services and products for <br />
            which personal data is being communicated to VibrantWear. <br />
            Please read this Privacy Policy carefully as it explains how VibrantWear uses your personal data and <br />
            how to exercise your rights. This Privacy Policy supplements the Terms & Conditions or any documents <br />
            or notices that may refer to this Privacy Policy. <br />
            Should you have any questions, you may directly contact VibrantWear by sending an email to <br />
            vibrantwearofficial@gmail.com. <br />
            2. Definitions <br />
            DATA means data about a living individual who can be identified from those data (or from those and <br />
            other information either in our possession or likely to come into our possession). <br />
            USAGE DATA is data collected automatically either generated by the use of Service or from Service <br />
            infrastructure itself (for example, the duration of a page visit). <br />
            COOKIES are small files stored on your device (computer or mobile device). <br />
            DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with <br />
            other persons) determines the purposes for which and the manner in which any personal data are, or <br />
            are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data. <br />
            DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the <br />
            data on behalf of the Data Controller. We may use the services of various Service Providers in order to <br />
            process your data more effectively. <br />
            DATA SUBJECT is any living individual who is the subject of Personal Data. <br />
            THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the <br />
            subject of Personal Data. <br />
            3. Legal context <br />
            We abide by the recommendations of the relevant authorities and have put in place an organization to <br />
            ensure our compliance with the regulatory framework established by the General Data Protection <br />
            Regulation (EU) 2016/679 of the European Parliament and of the Council (GDPR) and any other laws or <br />
            regulations relating to personal information that apply to us. <br />
            4. What is our role? <br />
            Under the GDPR, we are considered as a data controller. It means that we set the whys and hows we <br />
            process your personal information. For example, when you are visiting our website, we are in charge of <br />
            determining the purposes and the means that are necessary to administer, operate and manage our <br />
            users’ personal information that we collect from it. <br />
            Depending on the activity we perform on your data, we may also be considered as a data processor. <br />
            This means that you are our customer’s end user and that we are processing your data under the <br />
            instructions of our customer considered as a data controller. In this case, the data controller sets the <br />
            purposes and means of the processing activity, and we abide and deliver our service in regards to <br />
            these. <br />
            5. What kind of personal information do we <br />
            process? <br />
            We only collect and process personal information that is relevant and adequate. We give special <br />
            attention to its accuracy and updates when needed. Personal information includes in particular: <br />
            Type of data Examples of data <br />
            Economic and financial <br />
            data <br />
            e.g. income, financial situation, tax situation, banking details, <br />
            etc. <br />
            Identification data e.g. first name, last name, picture, birth date, etc. <br />
            Contact data e.g. email address, phone number, postal address, ect. <br />
            The collection of this information may at times be mandatory in order to provide our service, other <br />
            times optional to enhance your experience and left to your good will. Mandatory information will be <br />
            identified as such when we collect your data. Know that if you refuse to provide it, VibrantWear won’t <br />
            be able to provide you with its utmost service and you will unfortunately experience inconveniences. <br />
            6. When do we collect your personal <br />
            information? <br />
            We collect your personal information on various occasions. <br />
            Sources Description <br />
            Billing form Individual filled in a payment checkout <br />
            Online or paper <br />
            form <br />
            Individual filled in a form <br />
            Third Party Service We&apos;ve collected data through the use of a third party solution or <br />
            service <br />
            7. How do we use your personal information? <br />
            Your personal information will never be processed for incompatible purposes regarding why it was first <br />
            collected. We only collect and process personal information for specified, explicit and legitimate <br />
            purposes, like: <br />
            Processing Activities Purposes Legal basis <br />
            Payment & billing management To process money transactions Contractual duties <br />
            In order to comply with the principle of lawfulness, the legal bases for each data processing is <br />
            determined carefully and on a case-by-case basis in accordance with the list provided by Article 6 of <br />
            the GDPR. <br />
            We do not process your data or use automated decision making without your knowledge, nor do we <br />
            sell or rent your personal information without your explicit consent. <br />
            8. Who can access your personal information? <br />
            Recipients to whom we disclose your personal information are carefully chosen by us. They receive <br />
            data for legitimate purposes, especially when it comes to pursuing our business activity and providing <br />
            a qualitative service: <br />
            Subprocessor Service provided <br />
            Privacyboard GDPR compliance solution <br />
            Stripe Payment & billing management <br />
            Certain data recipients are considered our data processors in accordance with Article 28 of the GDPR, <br />
            which means we review how they handle personal information and make sure they put in place <br />
            appropriate guarantees to protect it. <br />
            Other recipients are considered authorized third parties in accordance with Article 4 of the GDPR, <br />
            which means we have to communicate your personal information to them to comply with applicable <br />
            legal obligations, lawful requests and processes (subpoenas, requests from government or tax <br />
            authorities, etc.). <br />
            9. Where do we transfer your personal <br />
            information? <br />
            As far as possible, your personal information is processed within the European Union. However, some <br />
            of our service providers may be located in another country of which you are a resident or pursuing <br />
            their activity outside of the European Union. <br />
            When we transfer your personal information to a recipient outside the European Union, we take care <br />
            of putting in place sufficient guarantees in accordance with the list provided by Articles 44 to 50 of the <br />
            GDPR, whether it is having it stored in a country with an adequate privacy protection or contracting <br />
            Data Protection Agreements to ensure your personal information is protected. <br />
            Subprocessor Location Adopted safeguard <br />
            Stripe USA Data Processing Agreement <br />
            10. How long do we store your personal <br />
            information? <br />
            As a general rule when we are considered a data controller by the GDPR, retention periods of your <br />
            personal information are determined according to the purposes for which we collected it and our legal <br />
            obligations. <br />
            Regarding our activities as a data processor, we retain our customers’ end users personal information <br />
            as long as required by our terms and conditions and the pursuing of the service our customers’ <br />
            subscribed to. <br />
            When these purposes are fulfilled or when you ask us, your personal information is archived, erased or <br />
            anonymized. <br />
            11. How do we protect your personal <br />
            information? <br />
            We care deeply about the safety of your personal information and that is why we put in place <br />
            adequate technical and organizational security measures to preserve its confidentiality, integrity and <br />
            availability. <br />
            We take into account the risks for your rights and freedoms and therefore follow with great care the <br />
            recommendations of the competent authorities regarding security. <br />
            12. What are your rights and how to exercise <br />
            them? <br />
            In accordance with Articles 12 to 23 of GDPR, you have rights over your personal information that we <br />
            are committed to respect: <br />
            you can request access to your personal information and a copy of it <br />
            you can ask us to modify your personal information if you consider it obsolete, inaccurate or <br />
            incomplete. <br />
            you can object to the processing of your personal information if based on our legitimate interest in <br />
            certain circumstances. <br />
            you can request to restrict the processing during a limited period of time, in certain circumstances. <br />
            you can opt-out from a consent already given, without this withdrawal affecting the lawfulness of <br />
            the processing operations already carried out. <br />
            when technically feasible, you can ask us to send you the personal information you provided us or <br />
            that we communicate it to a third party. <br />
            you can ask us to delete your personal information if it meets legal grounds for which it is <br />
            applicable. <br />
            These rights can be exercised directly and at any time by sending an email to <br />
            https://vibrantwear.vercel.app or on our Data Requests page. In the case you are our customer’s end <br />
            user, please take into consideration that this request will be forwarded and must be answered directly <br />
            by them. <br />
            13. Children&apos;s privacy <br />
            Our Services are not intended for use by children under the age of 13 (&quot;Children&quot;). <br />
            We do not knowingly collect personally identifiable information from Children under 13. If you become <br />
            aware that a Child has provided us with Personal Data, please contact us. If we become aware that we <br />
            have collected Personal Data from Children without verification of parental consent, we take steps to <br />
            remove that information from our servers. <br />
            14. Policy changes <br />
            This Privacy Policy may be modified in the future to keep it updated with legal jurisprudence and <br />
            evolution. You&apos;ll be informed either by a special mention on this page or by a personalized warning, by <br />
            email for instance. <br />
            15. Contact us <br />
            If you have any questions about this Privacy Policy, please contact us via email at <br />
            vibrantwearofficial@gmail.com <br />
        </pre>
    );
};

export default PrivacyPolicy;